version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: password123
    restart: unless-stopped
    ports:
      - '5432:5432' # Expose for local development
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379' # Expose for local development
    volumes:
      - redis_data:/data

  server:
    build: .
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'dev-secret-key-for-development-only'
      DATABASE_URL: 'postgresql://docmost:password123@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      NODE_ENV: 'development'
      PORT: '3000'
      DEBUG_MODE: 'true'
      DISABLE_REGISTRATION: 'false'
      DISABLE_TELEMETRY: 'true'
      JWT_TOKEN_EXPIRES_IN: '30d'
      FILE_UPLOAD_SIZE_LIMIT: '200mb'
      STORAGE_DRIVER: 'local'
    ports:
      - '3001:3000' # Backend on different port
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

volumes:
  docmost:
  db_data:
  redis_data:
